// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/status/common.proto

package status

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultStatus int32

const (
	ResultStatus_Success       ResultStatus = 0
	ResultStatus_MaxLimit      ResultStatus = 1
	ResultStatus_Repeated      ResultStatus = 2
	ResultStatus_NotExisted    ResultStatus = 3
	ResultStatus_DBException   ResultStatus = 4
	ResultStatus_Empty         ResultStatus = 5
	ResultStatus_TokenEmpty    ResultStatus = 6
	ResultStatus_TokenMiss     ResultStatus = 7
	ResultStatus_TokenUnusable ResultStatus = 8
	ResultStatus_Prohibition   ResultStatus = 9
	ResultStatus_NotMatch      ResultStatus = 10
	ResultStatus_FormatError   ResultStatus = 11
)

var ResultStatus_name = map[int32]string{
	0:  "Success",
	1:  "MaxLimit",
	2:  "Repeated",
	3:  "NotExisted",
	4:  "DBException",
	5:  "Empty",
	6:  "TokenEmpty",
	7:  "TokenMiss",
	8:  "TokenUnusable",
	9:  "Prohibition",
	10: "NotMatch",
	11: "FormatError",
}

var ResultStatus_value = map[string]int32{
	"Success":       0,
	"MaxLimit":      1,
	"Repeated":      2,
	"NotExisted":    3,
	"DBException":   4,
	"Empty":         5,
	"TokenEmpty":    6,
	"TokenMiss":     7,
	"TokenUnusable": 8,
	"Prohibition":   9,
	"NotMatch":      10,
	"FormatError":   11,
}

func (x ResultStatus) String() string {
	return proto.EnumName(ResultStatus_name, int32(x))
}

func (ResultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_646a8dd68e24f450, []int{0}
}

type Request struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_646a8dd68e24f450, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Response struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_646a8dd68e24f450, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("omo.msp.status.ResultStatus", ResultStatus_name, ResultStatus_value)
	proto.RegisterType((*Request)(nil), "omo.msp.status.Request")
	proto.RegisterType((*Response)(nil), "omo.msp.status.Response")
}

func init() {
	proto.RegisterFile("proto/status/common.proto", fileDescriptor_646a8dd68e24f450)
}

var fileDescriptor_646a8dd68e24f450 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbb, 0x4e, 0x2b, 0x31,
	0x10, 0x86, 0xcf, 0x1e, 0x72, 0xdb, 0xc9, 0x05, 0xe3, 0x0a, 0x0a, 0x10, 0x4a, 0x85, 0x28, 0x92,
	0x82, 0x37, 0x88, 0x58, 0x2a, 0x12, 0xa1, 0x0d, 0x34, 0x74, 0x8e, 0x33, 0x52, 0x2c, 0xe2, 0x1d,
	0xe3, 0x99, 0x95, 0x96, 0x07, 0xe4, 0xbd, 0x90, 0x1d, 0x21, 0xd1, 0xfd, 0xdf, 0x7c, 0xa3, 0x7f,
	0xa4, 0x81, 0xab, 0x10, 0x49, 0x68, 0xc9, 0x62, 0xa4, 0xe5, 0xa5, 0x25, 0xef, 0xa9, 0x59, 0xe4,
	0x99, 0x9e, 0x91, 0xa7, 0x85, 0xe7, 0xb0, 0x38, 0xc9, 0xf9, 0x35, 0x0c, 0x6b, 0xfc, 0x6c, 0x91,
	0x45, 0x6b, 0xe8, 0x59, 0xda, 0xe3, 0x65, 0x71, 0x5b, 0xdc, 0x95, 0x75, 0xce, 0xf3, 0x1b, 0x18,
	0xd5, 0xc8, 0x81, 0x1a, 0xc6, 0xe4, 0xf7, 0x46, 0xcc, 0xaf, 0x4f, 0xf9, 0xfe, 0xbb, 0x80, 0x49,
	0x8d, 0xdc, 0x1e, 0x65, 0x9b, 0xfb, 0xf4, 0x18, 0x86, 0xdb, 0xd6, 0x5a, 0x64, 0x56, 0xff, 0xf4,
	0x04, 0x46, 0x6b, 0xd3, 0x3d, 0x3b, 0xef, 0x44, 0x15, 0x89, 0x6a, 0x0c, 0x68, 0x04, 0xf7, 0xea,
	0xbf, 0x9e, 0x01, 0x6c, 0x48, 0xaa, 0xce, 0x71, 0xe2, 0x33, 0x7d, 0x0e, 0xe3, 0xc7, 0x55, 0xd5,
	0x59, 0x0c, 0xe2, 0xa8, 0x51, 0x3d, 0x5d, 0x42, 0xbf, 0xf2, 0x41, 0xbe, 0x54, 0x3f, 0xed, 0xbe,
	0xd2, 0x07, 0x36, 0x27, 0x1e, 0xe8, 0x29, 0x94, 0x99, 0xd7, 0x8e, 0x59, 0x0d, 0xf5, 0x05, 0x4c,
	0x33, 0xbe, 0x35, 0x2d, 0x9b, 0xdd, 0x11, 0xd5, 0x28, 0xb5, 0xbd, 0x44, 0x3a, 0xb8, 0x9d, 0xcb,
	0x6d, 0x65, 0x3a, 0xbe, 0x21, 0x59, 0x1b, 0xb1, 0x07, 0x05, 0x49, 0x3f, 0x51, 0xf4, 0x46, 0xaa,
	0x18, 0x29, 0xaa, 0xf1, 0x6a, 0xf6, 0x3e, 0xf9, 0xfb, 0xb3, 0xdd, 0x20, 0xd3, 0xc3, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x29, 0x1c, 0x3e, 0x04, 0x4a, 0x01, 0x00, 0x00,
}
