// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/status/common.proto

package status

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultStatus int32

const (
	ResultStatus_Success        ResultStatus = 0
	ResultStatus_MaxLimit       ResultStatus = 1
	ResultStatus_Repeated       ResultStatus = 2
	ResultStatus_NotExisted     ResultStatus = 3
	ResultStatus_DBException    ResultStatus = 4
	ResultStatus_Empty          ResultStatus = 5
	ResultStatus_TokenEmpty     ResultStatus = 6
	ResultStatus_TokenMiss      ResultStatus = 7
	ResultStatus_TokenUnusable  ResultStatus = 8
	ResultStatus_Prohibition    ResultStatus = 9
	ResultStatus_NotMatch       ResultStatus = 10
	ResultStatus_FormatError    ResultStatus = 11
	ResultStatus_DownloadFailed ResultStatus = 12
	ResultStatus_ServerError    ResultStatus = 13
	ResultStatus_VerifyFailed   ResultStatus = 98
	ResultStatus_MustBind       ResultStatus = 99
	ResultStatus_UserNotExisted ResultStatus = 1001
	ResultStatus_UserRepeated   ResultStatus = 1002
	ResultStatus_UserFreeze     ResultStatus = 1003
	ResultStatus_SNSWechat      ResultStatus = 1101
)

var ResultStatus_name = map[int32]string{
	0:    "Success",
	1:    "MaxLimit",
	2:    "Repeated",
	3:    "NotExisted",
	4:    "DBException",
	5:    "Empty",
	6:    "TokenEmpty",
	7:    "TokenMiss",
	8:    "TokenUnusable",
	9:    "Prohibition",
	10:   "NotMatch",
	11:   "FormatError",
	12:   "DownloadFailed",
	13:   "ServerError",
	98:   "VerifyFailed",
	99:   "MustBind",
	1001: "UserNotExisted",
	1002: "UserRepeated",
	1003: "UserFreeze",
	1101: "SNSWechat",
}

var ResultStatus_value = map[string]int32{
	"Success":        0,
	"MaxLimit":       1,
	"Repeated":       2,
	"NotExisted":     3,
	"DBException":    4,
	"Empty":          5,
	"TokenEmpty":     6,
	"TokenMiss":      7,
	"TokenUnusable":  8,
	"Prohibition":    9,
	"NotMatch":       10,
	"FormatError":    11,
	"DownloadFailed": 12,
	"ServerError":    13,
	"VerifyFailed":   98,
	"MustBind":       99,
	"UserNotExisted": 1001,
	"UserRepeated":   1002,
	"UserFreeze":     1003,
	"SNSWechat":      1101,
}

func (x ResultStatus) String() string {
	return proto.EnumName(ResultStatus_name, int32(x))
}

func (ResultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_646a8dd68e24f450, []int{0}
}

type Request struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_646a8dd68e24f450, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Response struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_646a8dd68e24f450, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("omo.msp.status.ResultStatus", ResultStatus_name, ResultStatus_value)
	proto.RegisterType((*Request)(nil), "omo.msp.status.Request")
	proto.RegisterType((*Response)(nil), "omo.msp.status.Response")
}

func init() {
	proto.RegisterFile("proto/status/common.proto", fileDescriptor_646a8dd68e24f450)
}

var fileDescriptor_646a8dd68e24f450 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x41, 0x6f, 0xd3, 0x40,
	0x10, 0x85, 0x49, 0x69, 0x6b, 0x7b, 0xe2, 0xb8, 0xcb, 0x70, 0x81, 0x03, 0x08, 0xf5, 0x84, 0x38,
	0xa4, 0x07, 0xfe, 0x41, 0x54, 0xe7, 0x44, 0x22, 0x64, 0x53, 0x90, 0xb8, 0xad, 0xd7, 0x83, 0xb2,
	0xc2, 0xf6, 0x98, 0xdd, 0x31, 0x24, 0xfc, 0x47, 0x4e, 0xfc, 0x0a, 0xe0, 0x4f, 0xa0, 0xdd, 0x40,
	0x95, 0xdb, 0x7c, 0xef, 0x3d, 0x3d, 0xfb, 0x69, 0xe1, 0xe9, 0xe8, 0x58, 0xf8, 0xc6, 0x8b, 0x96,
	0xc9, 0xdf, 0x18, 0xee, 0x7b, 0x1e, 0x96, 0x51, 0xc3, 0x82, 0x7b, 0x5e, 0xf6, 0x7e, 0x5c, 0x1e,
	0xcd, 0xeb, 0x67, 0x90, 0x54, 0xf4, 0x65, 0x22, 0x2f, 0x88, 0x70, 0x6e, 0xb8, 0xa5, 0x27, 0xb3,
	0x17, 0xb3, 0x97, 0x59, 0x15, 0xef, 0xeb, 0xe7, 0x90, 0x56, 0xe4, 0x47, 0x1e, 0x3c, 0x05, 0xbf,
	0xd5, 0xa2, 0xff, 0xfb, 0xe1, 0x7e, 0xf5, 0xf3, 0x0c, 0xf2, 0x8a, 0xfc, 0xd4, 0x49, 0x1d, 0xfb,
	0x70, 0x0e, 0x49, 0x3d, 0x19, 0x43, 0xde, 0xab, 0x07, 0x98, 0x43, 0xba, 0xd1, 0xfb, 0x37, 0xb6,
	0xb7, 0xa2, 0x66, 0x81, 0x2a, 0x1a, 0x49, 0x0b, 0xb5, 0xea, 0x0c, 0x0b, 0x80, 0x2d, 0x4b, 0xb9,
	0xb7, 0x3e, 0xf0, 0x43, 0xbc, 0x82, 0xf9, 0xed, 0xaa, 0xdc, 0x1b, 0x1a, 0xc5, 0xf2, 0xa0, 0xce,
	0x31, 0x83, 0x8b, 0xb2, 0x1f, 0xe5, 0xa0, 0x2e, 0x42, 0xf6, 0x1d, 0x7f, 0xa6, 0xe1, 0xc8, 0x97,
	0xb8, 0x80, 0x2c, 0xf2, 0xc6, 0x7a, 0xaf, 0x12, 0x7c, 0x04, 0x8b, 0x88, 0x77, 0xc3, 0xe4, 0x75,
	0xd3, 0x91, 0x4a, 0x43, 0xdb, 0x5b, 0xc7, 0x3b, 0xdb, 0xd8, 0xd8, 0x96, 0x85, 0x8f, 0x6f, 0x59,
	0x36, 0x5a, 0xcc, 0x4e, 0x41, 0xb0, 0xd7, 0xec, 0x7a, 0x2d, 0xa5, 0x73, 0xec, 0xd4, 0x1c, 0x11,
	0x8a, 0x5b, 0xfe, 0x36, 0x74, 0xac, 0xdb, 0xb5, 0xb6, 0x1d, 0xb5, 0x2a, 0x0f, 0xa1, 0x9a, 0xdc,
	0x57, 0x72, 0xc7, 0xd0, 0x02, 0x15, 0xe4, 0xef, 0xc9, 0xd9, 0x4f, 0x87, 0x7f, 0x91, 0x26, 0x0e,
	0x9c, 0xbc, 0xac, 0xec, 0xd0, 0x2a, 0x83, 0x8f, 0xa1, 0xb8, 0xf3, 0xe4, 0x4e, 0x66, 0xfd, 0x0a,
	0x3f, 0x97, 0x07, 0xf1, 0x7e, 0xf9, 0xef, 0x04, 0xaf, 0x00, 0x82, 0xb4, 0x76, 0x44, 0xdf, 0x49,
	0xfd, 0x49, 0xb0, 0x80, 0xac, 0xde, 0xd6, 0x1f, 0xc8, 0xec, 0xb4, 0xa8, 0x1f, 0xe9, 0xaa, 0xf8,
	0x98, 0x9f, 0xbe, 0x60, 0x73, 0x19, 0xe9, 0xf5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0x13,
	0xc2, 0x53, 0xd8, 0x01, 0x00, 0x00,
}
